### ISSUE TITLE
rnaseq pipeline w/SRA: ambiguous rules

### ISSUE THREAD

**Issue by palmercd** [lcdb/lcdb-wf#139]
Trying to run RNA-seq pipeline with built-in SRA (single end) download support, snakemake dies with ambiguous rule exception for the rules fastq_dump and cutadapt. Workaround --allow-ambiguity allows the run to complete successfully, but obviously that's hackjob nonsense. Sorry I don't have actual fix suggestions, I defer to y'all snakemake masters.

**Comment by daler** [comment]
Thanks, sorry just seeing this now. Should be fixed now, specifically from this commit: https://github.com/lcdb/lcdb-wf/pull/140/commits/120ed1a9d02554450fe2e137b7ac6368286d61be
