### ISSUE TITLE
downloading references (during rnaseq) gitpython unavailable

### ISSUE THREAD

**Issue by palmercd** [lcdb/lcdb-wf#143]
download_and_process fails for reference fasta and gtf downloads during a fresh rnaseq pipeline run, complaining about gitpython being unavailable. Manual installation of gitpython with conda resolves the problem.

**Comment by daler** [comment]
That is super weird. Do you have the reference config that caused this? A fasta coming from a git repo or something? If not, only thing I can think of is that some dependency has an unspecified dependency on gitpython. Maybe snakemake itself?

I see gitpython was added [as a snakemake dep](https://bitbucket.org/snakemake/snakemake/annotate/c0cbe5bf7d9a46f8ee5d355638a73014762f7bbe/environment.yml?at=master&fileviewer=file-view-default#environment.yml-33) in August, but it's not specified in the [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/snakemake/meta.yaml#L14). It is however in the [snakemake-minimal](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/snakemake-minimal/meta.yaml#L44) package.  I'll ask Johannes.

**Comment by daler** [comment]
Nevermind, the `snakemake` conda package includes the `snakemake-minimal` package, so `gitpython` should be coming in too.

My best guess is that your current conda-installed snakemake dates to the time at which snakemake was split into the full and minimal conda packages, and possibly gitpython was missed as a dep during that time . . . .?

**Comment by palmercd** [comment]
OK this one is just bizarre, but confirmed, it's getting pulled in now. As of... _not very many hours ago_ this was not the case. I checked it two more times after the first instance of it.

Thank you for checking, and I'm very sorry for the inconvenience.
