### ISSUE TITLE
revert gtf postprocess for Drosophila flybase conversion_refflat

### ISSUE THREAD

**Issue by palmercd** [lcdb/lcdb-wf#144]
The current reference_configs/Drosophila_melanogaster configuration file does not work with flybase _Drosophila_ reference data, which is to say, master is not in a functional state. The generic postprocessing function common/convert_gtf_chroms is missing functionality from the previous dm6/gtf_postprocess:

`"""| awk -F "\\t" '{{OFS="\\t"; if ( ! ($7 != "-" && $9 ~ /FBgn0002781/)) print $0}}' """`

The FBgn0002781 match and filter is still necessary in at least <= r6-24. The pipeline crashes at conversion_refflat with an error from gtfToGenePred regarding - strand content from FBgn0002781.

**Comment by daler** [comment]
Thanks

@esnaultc I think we need a post-process function to remove arbitrary genes possibly constrained to a strand . . .

Can you please:
- [ ] make a new module `lib/postprocess/utils.py`
- [ ] add a function to that module that takes additional args for string to match in the 9th field of GTF and an optional strand that defaults to None; if the pattern is found and the provided strand match then exclude the line
- [ ] move `lib.common.convert_gtf_chroms` and `lib.common.convert_fasta_chroms` from to `lib.postprocess.utils`
- [ ] add a test for the new gene-remover function

**Comment by daler** [comment]
closing, as b9fd5cd99ac856eb fixed this:

- [new post-process function](https://github.com/lcdb/lcdb-wf/blob/master/lib/postprocess/utils.py#L10)
- [updated config that uses it](https://github.com/lcdb/lcdb-wf/blob/master/include/reference_configs/Drosophila_melanogaster.yaml#L19)
