### ISSUE TITLE
Paired end support broken

### ISSUE THREAD

**Issue by palmercd** [lcdb/lcdb-wf#162]
Paired end support fails at first step (symlink_targets) by symlinking R1 and R2 both to the R1 input file. All downstream rules continue without errors, as apparently hisat2 allows embedded mates to map successfully. bowtie2 (in fastq_screen) doesn't seem to, but since fastq_screen is only operating on R1, this doesn't come up. This would also be flagged by insert size distribution but that is not presented in multiqc.

Confirmed only for rnaseq.

**Comment by daler** [comment]
See #164 for the fix!

**Comment by daler** [comment]
This fix has now been merged into master, can you double check this fixes the issue?

**Comment by palmercd** [comment]
Confirmed, symlinks are now correctly assigned for PE, thank you!
