### ISSUE TITLE
rnaseq workflow failure for fixed patterns

### ISSUE THREAD

**Issue by palmercd** [lcdb/lcdb-wf#163]
Rules depending on invariant patterns from config/rnaseq_patterns.yaml do not evaluate correctly. It seems to possibly return null? This is detectable immediately as workflow will not launch due to indexing error when trying to evaluate

workflows/rnaseq/Snakefile line 624, log: c.targets['multiqc'][0] + '.log'

With that fixed (replace with actual string path and filename), the workflow can run but all rules with outputs of fixed patterns (rnaseq_rmarkdown, multiqc, libsizes_table, rrna_percentages_table) silently fail to run. No data/rnaseq_aggregation directory is created, and differential expression is not run.

Appears to be a software version issue of some kind, as this has suddenly appeared in new and old instances of the workflow with newly constructed environments.

**Comment by daler** [comment]
This is from the latest Snakemake version, and the v1.3rc branch fixes this -- specifically see https://github.com/lcdb/lcdb-wf/pull/157/commits/8a2111229a98da2656255f8616eefb30833052a4#diff-92a7e833dd6f7d09d98c4ec9c1b56484R29 which details why it's happening and the fix.
