### ISSUE TITLE
evaluate individual vs pooled featureCounts runs

### ISSUE THREAD

**Issue by daler** [lcdb/lcdb-wf#181]
Currently we keep the featureCounts runs separate (one run per BAM) which allows us to check individual samples. If featureCounts is run once with all BAMs, does multiqc still pull out the per-sample metrics? If so, it would make it a little more straightforward to load counts into R.

**Comment by njohnso6** [comment]
This evaluation was successful. Decided to pool featureCounts runs in the future. Will fix in issue #191

**Comment by daler** [comment]
Closing; see #191 for implementation.
