### ISSUE TITLE
top.plots rewrite

### ISSUE THREAD

**Issue by daler** [lcdb/lcdb-wf#224]
The top.plots in helpers.Rmd isn't very convenient to use or customize. Better would be to have a function that returns a tidy dataframe that includes all metadata from `colData(dds)` that can be used for arbitrary ggplot plotting.

I'm thinking a signature like this, where sel.genes can optionally be a list of genes to consider (otherwise you get the whole thing):

```r
counts.df <- function(dds, sel.genes=NULL)
```

that returns a dataframe with columns like:

```
gene  normalized_count  samplename  rank replicate  group <other columns from colData(dds)>
```

(where rank is log2foldchange)

that we can plot with 

```r
ggplot(df %>% filter(rank <= 3) +
  aes(y=count, x=group, color=group) +
  geom_point() +
  facet_grid(.~rank)
```
It's nice to have the convenient gene names as titles like we have now -- not quite sure yet how best to implement that. Maybe the function should create an additional "nice label" column?

**Comment by esnaultc** [comment]
Should rank be based on padj? the genes are sorted using `padj.order` currently.

**Comment by daler** [comment]
I think so -- probably also worth giving the option of sorting by log2FoldChange.

**Comment by daler** [comment]
closing, as these have been removed from the static html output in favor of interactive plotting in the shiny app
