### ISSUE TITLE
Clarify error message for 'get_techreps' function

### ISSUE THREAD

**Issue by hertafeldsr** [lcdb/lcdb-wf#243]
When setting up a chipseq experiment, I was a little thrown off by the error message in the get_techreps function in common.py (called by the 'merge_techreps' rule in the Snakefile). The issue was that I had a typo in the config file in a few of the 'ip' fields that caused them to not match with the corresponding value in the label column in the sampletable. The error message said 

"No technical replicates found for label 'example'. This looks to be a chIP-seq experiment; check the peak-calling section of the config. "

The experiment I was setting up didn't have any technical replicates, so this wording confused me because I thought it was saying that the workflow requires technical replicates to run properly, and that it was throwing the error because I didn't have any. It might be clearer to say something like

"No technical replicates found in sampletable for label 'example' from the config file. This looks to be a chIP-seq experiment; check the peak-calling section of the config to ensure that the 'ip' and 'control' entries match their corresponding 'label' entries in the sampletable. "

**Comment by daler** [comment]
Fixed in 0d8f5ffab3335350367b080adee39a80b3f05998.
