### ISSUE TITLE
Note in documentation the need to change 'patterns_targets.py' if not using all three algorithms (macs2, sicer, and spp) in chipseq config

### ISSUE THREAD

**Issue by hertafeldsr** [lcdb/lcdb-wf#244]
The file 'patterns_targets.py' expects an entry for each algorithm in the peak_calling section of the config file, as it creates a list ("PEAK_CALLERS = ['macs2', 'spp', 'sicer']") and loops through them to set up the peak calling runs. One solution would be to clarify in the config file the need to edit that list in 'patterns_targets.py' if the user is not using all three algorithms. Another solution would be to edit 'patterns_targets.py' to do some extra parsing of the config file to only loop through algorithms that are listed there.

**Comment by daler** [comment]
I believe this is fixed in a9afebc0b8909a41d1b1bfeed80c2d80bb33e798
