### ISSUE TITLE
GSEA rather than overrepresentation?

### ISSUE THREAD

**Issue by daler** [lcdb/lcdb-wf#262]
When splitting off the functional enrichment analysis (see #259), we should consider including options to use GSEA or overrepresentation, and writing the rest of the code to be suitably agnostic to the method.

**Comment by mitraak** [comment]
- Adding a parameter in the main `rnaseq.Rmd` to set functional enrichment mode to overrepresentation or gsea. This is needed since overrep works on DE genes, while gsea works on the entire ranked list.
    - this is passed to the child Rmd via the `params=` parameter in the `rmarkdown::render` call

TODO:
- add option to output GSEA-ready genelists

**Comment by mitraak** [comment]
- TODO
    - add general helper function to convert EntrezID to symbols for gseaResult
    - move KEGG id conversion code to helper function

**Comment by mitraak** [comment]
- most of these are done
- potential additional TODO:
    - add GSEA plot options?

**Comment by daler** [comment]
this is implemented in v1.9
