### ISSUE TITLE
Add more contrast examples

### ISSUE THREAD

**Issue by mitraak** [lcdb/lcdb-wf#268]
Have different examples of ways to specify contrasts in the results chunk
- character vector, e.g. `contrast = c('group', 'treatment', 'control')`
- numeric vector, e.g. `contrast = c(1, 0, -1, 0)`

Maybe other examples of different ways can also be added, e.g. using a `resultsNames` value

**Comment by daler** [comment]
This has been done for a while -- see [the ReST](https://github.com/lcdb/lcdb-wf/blob/master/docs/rnaseq-rmd.rst#specifying-contrasts) and [built docs](https://lcdb.github.io/lcdb-wf/rnaseq-rmd.html#specifying-contrasts).
