### ISSUE TITLE
dupradar fails with hist

### ISSUE THREAD

**Issue by jfear** [lcdb/lcdb-wf#28]
I have come across some samples that fail with dupradar with the following:

```
Error in hist.default(dm$mhRate, breaks = 50, main = basename(bam), xlab = "Multimapping rate per gene", :
character(0)
Calls: hist -> hist.default
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
Execution halted
```

I am thinking the easiest solution is to wrap each plotting function with a `try` statement and then just output an empty image. However, that could potentially mask other problem. 

I need to figure out what the core of the problem is before doing anything.

**Comment by daler** [comment]
I believe, 10 months later, that this is still an issue -- dupradar rules are commented out in current version.
