### ISSUE TITLE
AnnotationHub issues on biowulf

### ISSUE THREAD

**Issue by mitraak** [lcdb/lcdb-wf#282]
The first time we run the `rnaseq.Rmd` on biowulf, the annotationHub download step fails with the error:

```
Cannot determine internet connection.
 If you experience connection issues consider using 'localHub=TRUE'
Quitting from lines 76-106 (rnaseq.Rmd)
Error in bfcadd(bfc, rname = paste0(tolower(.class), ".sqlite3"), fpath = remote_db,   :
   is.character(proxy) is not TRUE
```

I believe we had fixed this issue in the past, so it's not clear why it's popping up again.

Also, I don't get this error, when I run this on my local workstation.

**Comment by mitraak** [comment]
still no fix, the workaround for now is to run the Rmd for the first time on local workstation. Once the hub is downloaded, subsequent runs work on biowulf.

**Comment by daler** [comment]
FIxed in https://github.com/lcdb/lcdb-wf/pull/265/commits/0fd2587b54393c05c6b1871f2895f97fd9ee2795
