### ISSUE TITLE
Update PhiX reference

### ISSUE THREAD

**Issue by esnaultc** [lcdb/lcdb-wf#318]
The URL for PhiX pointing to the Illumina FTP is no longer working. It needs to be updated to ftp://ftp.ncbi.nlm.nih.gov/genomes/Viruses/enterobacteria_phage_phix174_sensu_lato_uid14015/NC_001422.fna in the [PhiX.yaml]( https://github.com/lcdb/lcdb-wf/blob/v1.6rc/include/reference_configs/PhiX.yaml#L5).

Postprocesses need to be adjusted accordingly.

**Comment by daler** [comment]
This is fixed in 5b6b8747 and 5c49934b.
