### ISSUE TITLE
add samtools idxstats

### ISSUE THREAD

**Issue by daler** [lcdb/lcdb-wf#341]
It would be helpful to include `samtools idxstats` to help with evaluating reads on chromosome.

May require patching multiqc config as in https://multiqc.info/docs/#idxstats, and that might get a little crazy with assemblies like zebrafish that have lots and lots of contigs in the assembly.

**Comment by fridells51** [comment]
Picking this up.

**Comment by daler** [comment]
Closed in #354, thanks @fridells51!
