### ISSUE TITLE
Update .gitignore to reflect v1.9rc changes

### ISSUE THREAD

**Issue by kcampbell824** [lcdb/lcdb-wf#358]
v1.9rc comes with some significant additions that we may or may not want to include in the .gitignore. Some examples of additions to the .gitignore are:
- workflows/rnaseq/downstream/functional-enrichment.html
- workflows/rnaseq/downstream/functional-enrichment_cache/
- workflows/rnaseq/downstream/functional-enrichment_files/
- workflows/rnaseq/downstream/Rplots.pdf
- *.Rds
- *.Rd (covers new additions to lib/lcdbwf/)

**Comment by NaincyKumariKnoldus** [comment]
Hey @kcampbell824 Can I do this please if you want?

**Comment by daler** [comment]
addressed in #360
