### ISSUE TITLE
ranseq.Rmd: Libraries loaded after function is referenced if parallel option is set in the config (v1.9)

### ISSUE THREAD

**Issue by fridells51** [lcdb/lcdb-wf#365]
If `parallel: TRUE` is set in the config, this code will be run in rnaseq.Rmd:

```
parallel <- config$parallel$parallel
if (config$parallel$parallel){
     register(MulticoreParam(config$parallel$cores))
}
```

The problem is that `register` comes from a library that is loaded downstream of this code block. Moving the library loading chunk up before this code runs will fix this

**Comment by daler** [comment]
This is being addressed in #356
