### ISSUE TITLE
Check featurecounts & sampletable sample names in dds construction when subset_counts is not provided

### ISSUE THREAD

**Issue by kcampbell824** [lcdb/lcdb-wf#369]
In the case where there are samples in the featurecounts columns that are *not* in the sampletable & the user doesn't provide `subset_counts = TRUE`, the error message is thrown `!subset_counts: invalid argument type`. This error message doesn't provide clear info on why this is failing because subset_counts is an optional param. In the same scenario (sampletable sample names are a subset of featurecounts) and user sets `subset_counts = FALSE`, a better error message is provided `The following samples are in the counts data but not in the sampletable. If this is intended, consider using subset_counts=TRUE`. Within `make_dds()`, we should check sampletable names against featurecounts names explicitly when subset_counts is not supplied & output a clearer error message.

**Comment by daler** [comment]
Thanks -- this is actually fixed in https://github.com/lcdb/lcdb-wf/pull/366/commits/6a5413bfc9753e8a7f528e354bc2c4604d563990, but it's still living in the v1.10 branch and so hasn't been merged into the master branch yet. I'll leave this open until then.

**Comment by daler** [comment]
Fixed in https://github.com/lcdb/lcdb-wf/commit/6a5413bfc9753e8a7f528e354bc2c4604d563990 and has been merged for a while now in v1.10, so closing.
