### ISSUE TITLE
Avoid overwriting combined.Rds in functional-enrichment.Rmd and gene-patterns.Rmd

### ISSUE THREAD

**Issue by menoldmt** [lcdb/lcdb-wf#392]
Problem:  

Currently, the same .Rds object (combined.Rds) is being used to transfer data from rnaseq.Rmd to functional-enrichment.Rmd to gene-patterns.Rmd. Since the modification time of this file is used in cached chunk options in the latter two files, the creation of the file at the end automatically invalidates the cache, making caching useless.  

Solution:  

Rnaseq.Rmd -> combined.Rds -> functional-enrichment.Rmd -> functional-enrichment-combined.Rds -> gene-patterns.Rmd -> gene-patterns-combined.Rds

To account for the case where a user wishes to run gene patterns without having run functional enrichment previously, there needs to be a condition added before [here](https://github.com/lcdb/lcdb-wf/blob/d4f87aa723464cdfade20f685bf00f7d9a7fa117/workflows/rnaseq/downstream/gene-patterns.Rmd#L33) where the combined.Rds would be loaded instead of functional-enrichment-combined.Rds in the case that functional-enrichment-combined.Rds does not exist.

**Comment by daler** [comment]
This is being handled in #399

**Comment by daler** [comment]
Handled in #399 which is in turn merged into main with v1.11.
