### ISSUE TITLE
Do we expect missing symbols, when building Ensembl to Symbol map?

### ISSUE THREAD

**Issue by jfear** [lcdb/lcdb-wf#46]
We have found that there are a number of "NA" in the `dmel_r6-*_SYMBOL.csv`. For examples `FBgn0000003`, even though it clearly has a gene name on FlyBase `7SLRNA:CR32864`.

- [ ] Does annotation hub include CRs?
- [ ] Is there a way to force CRs to be included
- [ ] Should we use FB's files for mapping FBgn to gene?

**Comment by daler** [comment]
This happens for many species; the current process is just to fill in missing symbols with `rownames(dds)` (which are usually ensembl IDs). For fly specifically, I think the solution would be to have postprocessing hook in the references config to patch the GTF, and pull the FB -> symbol mapping from there.
