### ISSUE TITLE
Kallisto index build fails

### ISSUE THREAD

**Issue by jfear** [lcdb/lcdb-wf#5]
Could you remind me why kallisto fails. If I remember it right it was something to do with conda. Just a place holder to remember to fix.

**Comment by daler** [comment]
sleuth doesn't install on osx because we can't get rhdf5 to build for bioconda on osx, is that what you mean?

**Comment by daler** [comment]
Using salmon instead of kallisto, so this ends up being irrelevant (though I think it works fine in conda now)
