### ISSUE TITLE
add deepTools fingerprint

### ISSUE THREAD

**Issue by daler** [lcdb/lcdb-wf#60]
plotFingerprint (http://deeptools.readthedocs.io/en/latest/content/feature/plotFingerprint_QC_metrics.html) would be a useful QC metric to include.

**Comment by HussainAther** [comment]
I'm confused. It looks like plotFingerprint is already in the deeptools wrapper?

**Comment by daler** [comment]
You're right, it's already in a wrapper and already in `chipseq.snakefile`. Somehow I completely forgot I had added it!

**Comment by jfear** [comment]
haha, I am glad I am not the only one who forgets when they have done stuff.
